#!/usr/bin/env bash
# Generated by scan-source from scan-2026-09-11_120947-report.md — REVIEW BEFORE RUNNING.
# Bumps the Windows/Python 3.12 pinned closure of EdgeMesh to versions with no known advisories.
# Edits tracked files in place (pyproject.toml, constraints/windows-py312.txt, .github/workflows/tests.yml).
# Run it on a branch. Validate on Windows afterwards: pip install --no-deps -r requirements-cpu-test.txt && pip check.
TARGET="/mnt/d/Documents/Code/GitHub/EdgeMesh"
FAILURES=0

step() {  # step "<description>" <command...>
  local desc="$1"; shift
  echo "==> $desc"
  if "$@"; then echo "    OK"; else echo "    FAILED: $desc" >&2; FAILURES=$((FAILURES+1)); fi
}

unfixable() {  # unfixable "<vuln>" "<why + what to do instead>"
  echo "ERROR: $1 — $2" >&2
  FAILURES=$((FAILURES+1))
}

# bump <file> <package> <old> <new> : replace an exact "package==old" pin; idempotent; tolerates CRLF line endings.
CR=$(printf '\r')
bump() {
  local file="$1" pkg="$2" old="$3" new="$4"
  if grep -qE "(^|[\"' ])${pkg}==${new}([\"' ,;${CR}]|$)" "$file"; then echo "    already at ${pkg}==${new}"; return 0; fi
  grep -qE "(^|[\"' ])${pkg}==${old}([\"' ,;${CR}]|$)" "$file" || { echo "    pin ${pkg}==${old} not found in $file" >&2; return 1; }
  sed -i -E "s/(^|[\"' ])${pkg}==${old}([\"' ,;${CR}]|$)/\1${pkg}==${new}\2/" "$file"
}

PY="$TARGET/pyproject.toml"
CON="$TARGET/constraints/windows-py312.txt"
WF="$TARGET/.github/workflows/tests.yml"

# --- pillow: 18 advisories (PSD/font/PDF/JPEG2000 memory corruption, decompression bombs), reachable via user images
step "pillow 11.3.0 -> 12.3.0 in pyproject.toml"                 bump "$PY"  pillow 11.3.0 12.3.0
step "pillow 11.3.0 -> 12.3.0 in constraints/windows-py312.txt"  bump "$CON" pillow 11.3.0 12.3.0

# --- torch: 8 advisories incl. weights_only unpickler bypass CVE-2026-24747; torchvision must match torch
step "torch 2.8.0 -> 2.13.0 in pyproject.toml"                   bump "$PY"  torch 2.8.0 2.13.0
step "torch 2.8.0 -> 2.13.0 in constraints/windows-py312.txt"    bump "$CON" torch 2.8.0 2.13.0
step "torchvision 0.23.0 -> 0.28.0 in pyproject.toml"            bump "$PY"  torchvision 0.23.0 0.28.0
step "torchvision 0.23.0 -> 0.28.0 in constraints"               bump "$CON" torchvision 0.23.0 0.28.0

# --- setuptools: CVE-2026-59890 (MANIFEST file inclusion); pinned in three places
step "setuptools 80.9.0 -> 83.0.0 in pyproject.toml build-system" bump "$PY"  setuptools 80.9.0 83.0.0
step "setuptools 80.9.0 -> 83.0.0 in constraints"                bump "$CON" setuptools 80.9.0 83.0.0
step "setuptools 80.9.0 -> 83.0.0 in .github/workflows/tests.yml" bump "$WF"  setuptools 80.9.0 83.0.0

# --- transitive packages with drop-in fixes (closure stays self-consistent; see report)
step "urllib3 2.5.0 -> 2.7.0 (CVE-2026-44431, CVE-2025-66418, CVE-2025-66471, CVE-2026-21441)" bump "$CON" urllib3 2.5.0 2.7.0
step "requests 2.32.5 -> 2.34.2 (CVE-2026-25645)"                bump "$CON" requests 2.32.5 2.34.2
step "werkzeug 3.1.3 -> 3.1.8 (CVE-2025-66221, CVE-2026-21860, CVE-2026-27199)" bump "$CON" werkzeug 3.1.3 3.1.8
step "flask 3.1.2 -> 3.1.3 (CVE-2026-27205)"                     bump "$CON" flask 3.1.2 3.1.3
step "click 8.3.0 -> 8.4.2 (CVE-2026-7246)"                      bump "$CON" click 8.3.0 8.4.2
step "filelock 3.19.1 -> 3.32.2 (CVE-2025-68146, CVE-2026-22701)" bump "$CON" filelock 3.19.1 3.32.2
step "fonttools 4.60.1 -> 4.63.0 (CVE-2025-66034)"               bump "$CON" fonttools 4.60.1 4.63.0
step "idna 3.10 -> 3.18 (CVE-2026-45409)"                        bump "$CON" idna 3.10 3.18
step "pygments 2.19.2 -> 2.20.0 (CVE-2026-4539)"                 bump "$CON" pygments 2.19.2 2.20.0

# --- transformers: cannot be fixed by editing pins
unfixable "transformers 4.56.2 (11 advisories, 5 with no fix; fixes start at 5.0.0, path traversal fixed in 5.10.0)" \
  "5.x changes the dependency closure (huggingface-hub 1.x + httpx/httpcore/h11/anyio/hf-xet, typer/rich/shellingham/markdown-it-py/mdurl, regex>=2025.10.22, safetensors>=0.8.0). Regenerate constraints/windows-py312.txt on Windows per docs/Dependency_Validation.md with transformers==5.14.1 (the version .venv_linux already runs), then bump the 'depth' extra in pyproject.toml and run pip check + unittest."

# --- verify: the only package left with advisories must be transformers
verify_constraints() {
  pip-audit -r "$CON" --no-deps --disable-pip -f json 2>/dev/null | python3 -c '
import json,sys
d=json.load(sys.stdin); bad=sorted({x["name"] for x in d["dependencies"] if x.get("vulns")})
print("    packages still flagged:", ", ".join(bad) or "none")
sys.exit(0 if bad <= ["transformers"] else 1)'
}
if command -v pip-audit >/dev/null 2>&1; then
  step "pip-audit the updated constraints (only transformers may remain)" verify_constraints
else
  echo "    pip-audit not on PATH; skip verification" >&2
fi

echo
if [ "$FAILURES" -gt 0 ]; then
  echo "$FAILURES step(s) failed or need manual action" >&2
  exit 1
fi
echo "All fixes applied — re-run the scan to confirm the counts drop"
